### ISSUE TITLE
Feature Req: Display Pallets/Bales to adjust Autoload-"Box"

### ISSUE THREAD

**Issue by Iunoi** [loki79uk/FS25_UniversalAutoload#153]
It would be great if the Autoload-Shop configurator allowed you to select pallets, bales, or similar items to configure the autoload box and see how many of them would fit in terms of height, width, and length.

**Comment by loki79uk** [comment]
The probelm with this is we don't even know the size of most items at that point.  The size of objects is not known until they are detected by the triggers, and the number that fits is not known until you try to load them.

The whole principle is that you make the box as big as you can, and then whatever fits will fit.  If you can't make it any bigger then it shouldn't really matter what you "could" fit because there isn't enough room anyway..

In FS22 I had a spreadsheet for heights, we could do something similar, but the best I can do for now is to display the actual size then you can do the maths yourself.

**Comment by doodooRGM** [comment]
Gibt es eine Möglichkeit die Box in der Größe anzupassen?
Bei meiner verwendeten Version 0.2.2.1 sind keine Anfasser mehr zu sehen.
Was mache ich falsch.

**Comment by loki79uk** [comment]
Closing as not planned.  It is a nice idea, but too much work for now without creating a load of new objects in the shop every time you change the pallet type..

_There is already a console command for testing pallets after purchase.  Bales and logs will be added soon._
