### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by JasonX2001** [loki79uk/FS25_UniversalAutoload#16]
Hi,

is there a posibility to donate you something?

**Comment by loki79uk** [comment]
I don't have anything like that set up as I'm too busy (or lazy).  I would have made all my mods anyway because I want them.  Just testing, reporting bugs and general feedback is already helping loads.

If you can void the leeching scum download sites (any site with advertising) that helps the modding community, and:
![excellent](https://github.com/user-attachments/assets/dfd11738-0ddf-42c2-8436-43db3596bc42)
