### ISSUE TITLE
Blank Settings tab

### ISSUE THREAD

**Issue by jethbrown** [loki79uk/FS25_UniversalAutoload#166]
Since most recent update, a blank settings tab shows up in the in-game menu.  If i don't load the mod it goes away.  If I load it, the blank settings tab comes back.  Game works fine with it, but it is a issue or something your working on :-).

**Comment by loki79uk** [comment]
Yes, sorry it was something I was working on and forgot to mention.  I took it out the release just now.

I did a bit more work on it since yesterday, but still a long way to go.  The idea is something like a "Mod Settings" page for all mods:

![image](https://github.com/user-attachments/assets/b2327626-2dd2-4db8-8dab-acb5133fa768)

**Comment by loki79uk** [comment]
I still need to decide where to put the global UAL settings..

**Comment by jethbrown** [comment]
Ok thanks, not game breaking so will play with it while you're working with
it.  Mod is great btw, Thanks for your hard work!

**Comment by loki79uk** [comment]
The latest release (20 mins ago) doesn't have it anyway: https://github.com/loki79uk/FS25_UniversalAutoload/releases
