### ISSUE TITLE
v0.3.2.0 shop unusable

### ISSUE THREAD

**Issue by tobias-trozowski** [loki79uk/FS25_UniversalAutoload#182]
First of all, thanks for your great work!

Sadly, the mod does not work for us at all. Having a dedicated server and UAL enabled makes the ingame shop unusable.

Issues seen so far:
- when showing vehicle details, 3d view is not rendered
- buy price is 0€
- lease price is 0€
[log_2024-12-23_00-49-53.txt](https://github.com/user-attachments/files/18223723/log_2024-12-23_00-49-53.txt)

**Comment by Mannie313** [comment]
G:/07 Landwirtschaftssimulatoren/Landwirtschaftssimulator 25/mods/FS25_UniversalAutoload/UniversalAutoloadInstaller.lua:952: attempt to index nil with 'spec_universalAutoload'
2024-12-23 01:24 Error: Running LUA method 'update'.


This is displayed with version 0.3.2.0

**Comment by malmi** [comment]
0.3.1.0 still works

**Comment by Bunyan1** [comment]
Agreed on shop being unusable.  When I go into the shop it functions normally until I click on an item to purchase.  Then when viewing it in the shop, the item will not display...doesn't matter if consumable, tractor, or whatever.  I disabled all my mods except UAL, and still could reproduce the error.  I didn't have the issue until 3.2.0 .

Playing single player on stock map.  Thanks for all the work!  I've LOVED this mod since I believe FS17 (?).

Thanks!

**Comment by MaggzWOT** [comment]
3.2.0 broken and cant download 3.1.0 to roll back. Why remove old versions?

**Comment by geeknessfr** [comment]
Loki missed a small detail at line 952 of the UniversalAutoloadInstaller.lua file, he'll fix it as soon as he's available. In the meantime, like some of you have already done, you can roll back to an older version. ([link to v0.3.1.0](https://github.com/loki79uk/FS25_UniversalAutoload/releases/tag/v0.3.1.0))

Thanks for your feedback and patience 😉

**Comment by loki79uk** [comment]
Sorry about that - I tested in workshop but forgot it could affect main shop..

Should be fixed now: https://github.com/loki79uk/FS25_UniversalAutoload/releases/tag/v0.3.2.1

**Comment by tobias-trozowski** [comment]
confirmed. issue solved.

Thank you!

**Comment by Bunyan1** [comment]
Thanks for the work!
