### ISSUE TITLE
Sugestion: Saving loading filter type.

### ISSUE THREAD

**Issue by Trivium1709** [loki79uk/FS25_UniversalAutoload#185]
![image](https://github.com/user-attachments/assets/6e6a23a2-3ec3-4eb3-a79e-0a70c198e4b5)
Currently the option to change the loading filter type always resets after reloading the game, is there a way to add a save state to the last option selected? Unless there's already a way to do it and I missed it.

**Comment by loki79uk** [comment]
It is supposed to save that when you save the game - let me check - but probably not until after Xmas now

**Comment by Trivium1709** [comment]
> It is supposed to save that when you save the game - let me check - but probably not until after Xmas now

Never saved for me even on fs22. And no worries take your time :)

**Comment by loki79uk** [comment]
> Never saved for me even on fs22. And no worries take your time :)

You are right - I just made a stupid mistake with the logic and never noticed, so it has been like that ever since 22, lol.

So when writing to the savegame file I had this to protect against writing a nil value:
```lua
	xmlFile:setValue(saveKey.."#loadingFilter", spec.currentLoadingFilter or true)
	xmlFile:setValue(saveKey.."#baleCollectionMode", spec.baleCollectionMode or false)
	xmlFile:setValue(saveKey.."#useHorizontalLoading", spec.useHorizontalLoading or false)
```

But in LUA using the OR operator like that means that currentLoadingFilter ALWAYS evaluates to true (unless it was nil)

The easiest fix is just to make the default false like the others.  I'll do it in the next release!

**Comment by Trivium1709** [comment]
> edit: as a bonus, I should get less bugs about "why won't it load this empty pallet?" :D
Good point, hopefully that will do it! Thanks a bunch!

**Comment by Trivium1709** [comment]
Can confirm its working now, thanks again!
