### ISSUE TITLE
 0.0.0.5 MP stuttering

### ISSUE THREAD

**Issue by Achimobil** [loki79uk/FS25_UniversalAutoload#26]
Client stutter on Dedi Server. Log is full
[server.log](https://github.com/user-attachments/files/17965478/server.log)
[log.txt](https://github.com/user-attachments/files/17965482/log.txt)

**Comment by loki79uk** [comment]
I think this is likely to have been caused by the bug of incomplete settings written to the settings file, e.g.:

```xml
        <vehicle configFileName="data/vehicles/piaggio/ape50/ape50.xml">
            <configuration selectedConfigs="ALL">
            </configuration>
        </vehicle>
```

instead of 
```xml
        <vehicle configFileName="data/vehicles/piaggio/ape50/ape50.xml">
            <configuration selectedConfigs="ALL">
                <loadingArea offset="0.000 0.553 -0.689" width="1.128035" length="1.350709" height="1.091209"/>
            </configuration>
        </vehicle>
```

The stuttering should not happen again with the latest release 
https://github.com/loki79uk/FS25_UniversalAutoload/releases/tag/v0.0.0.6

I will add further validation to stop the error from occuring in the first place.  I already made a note of where:
https://github.com/loki79uk/FS25_UniversalAutoload/blob/aa6d241977e5f5deab3811b73b6842f1222a8f41/UniversalAutoload.lua#L2183

**Comment by Achimobil** [comment]
works for me now
