### ISSUE TITLE
Alot of wasted space

### ISSUE THREAD

**Issue by Venomtron** [loki79uk/FS25_UniversalAutoload#32]
![20241130094043_1](https://github.com/user-attachments/assets/9c8a164f-5fa3-4fb4-b47a-e13f61340f31)

Farmtech DPW 1800
Lizard Dragon
Default length and width.
0.0.0.7

Not sure if its bug, or what other info you might want let me know if u need something else, this might be more of a suggestion, just seems weird to waste so much room on the trailers.

**Comment by geeknessfr** [comment]
I have the same issue sometimes, it's because the mod separate different type of pallet (not always... idk why... but I like this feature... but it could be cool to have an option to activate it or not ^^)

So, what I do in this case, I unload and reload the pallets then the mod use the whole trailer.

**Comment by hvdklauw** [comment]
Yeah, I widened it slightly for that trailer so it will fit 2 round bales next to eachother

**Comment by loki79uk** [comment]
> ![20241130094043_1](https://github.com/user-attachments/assets/9c8a164f-5fa3-4fb4-b47a-e13f61340f31)
> 
> Farmtech DPW 1800
> Lizard Dragon
> Default length and width.
> 0.0.0.7
> 
> Not sure if its bug, or what other info you might want let me know if u need something else, this might be more of a suggestion, just seems weird to waste so much room on the trailers. 

The difference between this version and the old one (for 22) is that not it is up to you to decide how big you want the load area to be.  If you want it wider just make it wider.  It will automatically find the surface, but I have not done anything at all to refine each trailer other than write a one-fits-all algorithm.  The difference now is that it will work on every trailer, but you can easily change it if it doesn't suit your requirements.

**Comment by loki79uk** [comment]
The other reason that there are some gaps is that UAL no longer does a "second pass" to fill in gaps as it did in FS22.  This may change in the future, but it is because the positional accuracy of the overlapBox engine function is just not as good as it was in FS22.  Maybe it is a bug and GIANTS will fix it, or maybe it is an engine optimisation and I need to find a workaround.  Either way we can't fill in spaces for now as we don't know where they are.

**Comment by loki79uk** [comment]
Closing as not planned for now.  This is just the penalty you get for loading mixed pallets.  Unloading and reloading should pack them properly again.  I will try to improve loading patterns if I ever get the overlapBox function to work like it did in FS22..
