### ISSUE TITLE
autoload wood

### ISSUE THREAD

**Issue by FS22fanCatholic** [loki79uk/FS25_UniversalAutoload#45]
I heard from someone else you are unable to autoload wood

**Comment by Kmiktze** [comment]
As far as i know wood autoload is not implemented yet.

**Comment by loki79uk** [comment]
Correct. It is on the front page under planned features:
```
PLANNED FEATURES:

- Menu for global settings (in shop)
- Set vehicle options in the shop before purchase
- Bale collection mode (already works with xml edit)
- Log trailers (can be configured, but do not load anything yet)
- Multiplayer synchronisation of ALL settings
- Show debugging display in multiplayer
- Custom key bindings
```

**Comment by loki79uk** [comment]
Closing as completed just for house keeping.  Don't worry, log loading will be implemented!

**Comment by onetaps** [comment]
Mister @loki79uk any chances of having that rather sooner than later? We all see the effort you're putting into fixing the current issues for basic pallets, bales etc to get it into some stable version but also having a logs for an extensive testing would be cool. Any estimation when can we expect to have something for alfa/beta testing ;) ? Or for now this has the lowest prio due to the number of other outstanding bugs

**Comment by loki79uk** [comment]
I can't say a timescale at the moment.  I have some urgent work to get MP super strength fully working and updated onto ModHub.  After that it is a choice between wood loading or a proper menu to select all the different gloabal and vehicle UAL settings.

**Comment by onetaps** [comment]
All good! Take your time and once again appreciate your great work ;)

**Comment by asundrus** [comment]
> I can't say a timescale at the moment. I have some urgent work on LumberJack to get MP super strength fully working and updated onto ModHub. After that it is a choice between wood loading or a proper menu to select all the different gloabal and vehicle UAL settings.

I vote for "a proper menu to select all the different gloabal and vehicle UAL settings." :)
