### ISSUE TITLE
Load area not transferred to server before vehicle creation in MP

### ISSUE THREAD

**Issue by MisterTimLol** [loki79uk/FS25_UniversalAutoload#69]
Hi, i cant seem to find how to edit the load area in multiplayer.
It has a verry small load area right now. And i can only pick up 1 pallet every time cause of this. I use the Profi Liner.

**Comment by loki79uk** [comment]
it is hard to see the KRONE area, because it is inside the curtain trailer.  You can turn on wire frame and just about see it, but for now it is probably easier to edit the xml in notepad.  Or just don't worry about testing that one, use a different trailer.

**Comment by MisterTimLol** [comment]
Im talking about the pickup area. It only picks up 1 pallet at a time.

**Comment by loki79uk** [comment]
After chatting on Discord, this is an issue that happens when buying a new vehicle in multiplayer only.  There is a problem that when buying a vehicle, the server does not get the UAL size information until AFTER it has created the vehicle.  And this is too late to change the size.

There are a few options to fix this in the long term:
1) constantly update the settings every time they change BUT then any mistakes will be saved
2) add a new button to "apply" settings before buying (my preferred option, but still requires work on the GUI)
3) try to intercept the "confirm" button click and use that instead

As a short term workaround, just restarting the server will correctly size the loading zone and triggers from the settings saved in the settings file.

**Comment by JasonX2001** [comment]
> After chatting on Discord, this is an issue that happens when buying a new vehicle in multiplayer only. There is a problem that when buying a vehicle, the server does not get the UAL size information until AFTER it has created the vehicle. And this is too late to change the size.
> 
> There are a few options to fix this in the long term:
> 
>     1. constantly update the settings every time they change BUT then any mistakes will be saved
> 
>     2. add a new button to "apply" settings before buying (my preferred option, but still requires work on the GUI)
> 
>     3. try to intercept the "confirm" button click and use that instead
> 
> 
> As a short term workaround, just restarting the server will correctly size the loading zone and triggers from the settings saved in the settings file.

We could change the box by changing them in the workshop afterwards and then change some minor thing, e.g. tires. Then click configure. That let us change the box after we bought the trailers. 
Thats how we changed the size of the box for the fliegl DPW 1800 because it had so much space left.

**Comment by loki79uk** [comment]
> We could change the box by changing them in the workshop afterwards and then change some minor thing, e.g. tires. Then click configure. That let us change the box after we bought the trailers. Thats how we changed the size of the box for the fliegl DPW 1800 because it had so much space left.

Good point, re-buying or editing the vehicle should work as a workaround too.  There should be no problem to send the settings to the server in time once there is a proper UI for UAL in the shop.
