### ISSUE TITLE
Issue with tree sapling pallets

### ISSUE THREAD

**Issue by brittan-peel** [loki79uk/FS25_UniversalAutoload#72]
I noticed that the sequence in which pallets and bales are loaded is different to FS22, not sure why? Maybe limitations? Anyway I went to load 6 tree sapling pallets onto the International CV Series and noticed they stacked instead of spread out. I know it doesn't matter, but esthetically it doesn't look great.  I'm not sure if this is an issue or is intended but I thought I would post this anyways. 

![image](https://github.com/user-attachments/assets/ba488f6f-f27d-4ca3-af76-0dbf746f3a17)

**Comment by loki79uk** [comment]
Okay thanks! in FS22 I had the concept of a "do not stack" flag.  but so far in 25 everything is treated the same.  I will try to find a common feature to detect when it should be used, but otherwise will just add these flags manually.   This is one of the downsides of automatic pallet detection - sometimes we might need to make exceptions..

**Comment by geeknessfr** [comment]
And also, if you want, there’s a key you can set in the control settings to switch to layer mode (or horizontal loading)

![image](https://github.com/user-attachments/assets/02621729-a1a1-4c97-b9b3-5fe65804718a)

**Comment by loki79uk** [comment]
I think I've fixed this one for the saplings at least..  Stacks poplar boxes, but not others.

![image](https://github.com/user-attachments/assets/db3ad234-1f73-41ea-aa42-519fa0300426)

**Comment by loki79uk** [comment]
Should be fixed now in latest release https://github.com/loki79uk/FS25_UniversalAutoload/releases
