### ISSUE TITLE
Controller support on PC

### ISSUE THREAD

**Issue by Ser-Enmei** [loki79uk/FS25_UniversalAutoload#76]
Will there is controller support for on PC, I tried mapping most of the main controls to the controller in the in game key bind settings but nothing works, no commands show for the controller in the keybind tooltip on the top right of the screen.

**Comment by geeknessfr** [comment]
On my game, I replaces the "Radio" shortcuts to load/unload or switch side to unload on my controller, and it works fine.

Do you have the keyboard controls showing ?

And then, because it's something that happened to me many times, when you set the controller shortcuts, do you click on "Save" before quitting the screen ? ... I don't know why, but there is not any confirmation before leaving this screen to save the settings...

**Comment by Ser-Enmei** [comment]
Okay, I can safely say my issues were user error. I reset my keybinds and did as Geeknessfr did by replacing the radio keybinds to the autoload mod and it now works for me. I will look at what other keybinds I don't need to make full use of this mod. Thanks for all your hard work.
