### ISSUE TITLE
Unknown entity id for 'object' in method 'delete'

### ISSUE THREAD

**Issue by loki79uk** [loki79uk/FS25_UniversalAutoload#85]
> I also have the problem that I can't load in multiplayer, so I didn't want to open a new issue. I have also just tested again with v0.0.0.14. The message that comes up is warning_UNIVERSALAUTOLOAD_NO_OBJECTS_FOUND
> 
> As a test object I used the Krone ProfiLiner and tried to load with “prefabricated walls”, “wood chips” and “seedlings”, both an existing and a new ProfiLiner. The pads were free standing, so nothing that would have blocked.
> 
> I had activated the debug as far as possible and here is the log and the config
> 
> [server_log_2024-12-05_00-44-51.txt](https://github.com/user-attachments/files/18015548/log_2024-12-05_00-44-51.txt) [client_log.txt](https://github.com/user-attachments/files/18015557/log.txt) [UniversalAutoload.xml.txt](https://github.com/user-attachments/files/18015550/UniversalAutoload.xml.txt)

So you have this error in the log:
`Script error in delete: Unknown entity id 369343 for 'object' in method 'delete'.`

I don't understand how that can happen, but it was in a pervious bug too: https://github.com/loki79uk/FS25_UniversalAutoload/issues/56

If anyone can find a way to reproduce this then I stand a better chance of fixing it!

_Originally posted by @loki79uk in https://github.com/loki79uk/FS25_UniversalAutoload/issues/53#issuecomment-2519562629_

**Comment by Be-Mann** [comment]
Since you have added extra debugging to the latest version, I wanted to give you an update here. I have tested with the new version and also rented the ProfiLiner. Maybe the logs from us will help you.

I know you can do it, I'm proud of your work and I hope we can help you find the error. If you need anything from us, please let us know.

[server_log.txt](https://github.com/user-attachments/files/18045968/server_log.txt)
[client_log.txt](https://github.com/user-attachments/files/18045972/client_log.txt)

**Comment by loki79uk** [comment]
So I still can't see what is happening - it seems to only be a problem for the client, and often (but not always) happens near:
`data/objects/pallets/woodBeamPallet/woodBeamPallet.i3d`
or `data/objects/pallets/fillablePallet/fillablePallet.i3d`

Can you tell me exactly what you were doing at the time when it happens?

If possible could you try a game with only UAL installed and see if it is still happening.

I would also try without `FS25_PlaceTerraformPaintAnywhere_KingMods` - I wouldn't trust anything from that morally corrupt bunch of expletives.  Use the original one from modeleicher https://www.farming-simulator.com/mod.php?mod_id=303356&title=fs2025

I also noticed you still have the old LumberJack - I'd recommend using the latest: 
https://github.com/loki79uk/FS25_LumberJack/releases (but that should not affect this bug)

**Comment by Be-Mann** [comment]
> Can you tell me exactly what you were doing at the time when it happens?

I'll make a video later and attach it, until then I'll describe it.
In my test: I have the sawmill on the Pantai in our dedicated multiplayer game state and tried to load the pallets there on site, I also rented a new vehicle so that this corresponds to the current version. But when I try to load, I always get the message "Es sind keine kompatiblen Waren zum Be- oder Entladen vorhaden".
But as I said, the other players also had the problem with their trailers with their pallets.
I can't remember which trailer it was, but it was about the red berry soup

> If possible could you try a game with only UAL installed and see if it is still happening.

I'll have to see if I can do that, since the server is used productively in multiplayer.

> I would also try without FS25_PlaceTerraformPaintAnywhere_KingMods - I wouldn't trust anything from that morally corrupt bunch of expletives. Use the original one from modelleicher https://www.farming-simulator.com/mod.php?mod_id=303356&title=fs2025

Yes I understand, but unfortunately it's not about painting or changing terrain, but about placing, because Giants still hasn't fixed the bug with “Blocked Area” when a map-built building is demolished.

> I also noticed you still have the old LumberJack - I'd recommend using the latest:
https://github.com/loki79uk/FS25_LumberJack/releases (but that should not affect this bug)

I have already seen that there is a new version, but we want to work mostly from the Modhub, and since the 1.1.0.0 is an R.C. it should be ready soon ;)

We just have newbies in the LS on the server, who only look in from time to time and I don't want to expect too much from them at the beginning.

**Comment by Be-Mann** [comment]
So with “v0.1.0.1” the problem is gone, therefore closed.

Only the ProfiLiner seems to have unusually small triggers in multiplayer Please check the values from the UniversalAutoload.xml for the ProfiLiner to see if they are correct. The profiLiner was purchased after adding the “v0.1.0.1”, but the UniversalAutoload.xml was not deleted before. But you can see for yourself.

https://github.com/user-attachments/assets/cc83780a-5c88-4c7d-9527-b7897e2af003

**Comment by loki79uk** [comment]
I guess this bug will come back, as I don't know what could have caused it and have not intentionally done anything that would prevent it.  Closing for now.
